
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 11 22:45:03 CLST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ARCHIVO = 12;
  public static final int INGRESA = 5;
  public static final int ENTERO = 13;
  public static final int TERMINA = 9;
  public static final int LISTA = 6;
  public static final int ERROR = 11;
  public static final int EOF = 0;
  public static final int DIRECCION = 15;
  public static final int CIERRA = 8;
  public static final int CREA = 3;
  public static final int error = 1;
  public static final int OCUPACION = 14;
  public static final int SIMBOLO = 10;
  public static final int NOMBRE = 16;
  public static final int ABRE = 4;
  public static final int MUESTRA = 7;
  public static final int INICIA = 2;
}

